version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directories:
      - /.github/actions
      - /.github/workflows
    schedule:
      interval: daily
  # Maintain dependencies for Devcontainers
  - package-ecosystem: devcontainers
    directories:
      - /.devcontainer
    schedule:
      interval: monthly
  # Maintain dependencies for Container Images
  - package-ecosystem: docker
    directories:
      - /build/img
    schedule:
      interval: weekly
