---
services:
  devcontainer:
    image: ubuntu:22.04
    # platform: linux/amd64
    # entrypoint: /sbin/init
    # privileged: true
    stdin_open: true
    tty: true
    working_dir: /root/workspace
    env_file:
      - .env
    volumes:
      - .:/root/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.gnupg:/root/.gnupg # fixme: investigate mounting as read-only
      - ~/.ssh:/root/.ssh:ro
      - ~/.zshrc:/root/.zshrc:ro
