---
services:
  devos:
    image: ghcr.io/anselmes/devos:main
    # platform: linux/amd64
    # entrypoint: /sbin/init
    # network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    user: root # note: required for /sbin/init
    working_dir: /home/devos/workspace
    # env_file:
    #   - .env
    volumes:
      - .:/home/devos/workspace
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/libvirt:/var/lib/libvirt
      - ~/.gitconfig:/home/devos/.gitconfig:ro
      - ~/.gnupg:/home/devos/.gnupg:ro
      - ~/.ssh:/home/devos/.ssh:ro
      - ~/.zshrc:/home/devos/.zshrc:ro
    ports:
      - 10022:22
      - 10080:80
      - 10443:443
      - 15900:5900
      - 16443:6443
