version: "3.9"
services:
  devcontainer:
    image: ghcr.io/sanselme/devcontainer:latest
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /workspace
    env_file:
      - .env
    volumes:
      - .:/workspace
    ports:
      - 10022:22
      - 10080:80
      - 10443:443
      - 15900:5900
      - 16443:6443
