name: DevOS

on:
  - workflow_call

permissions: read-all

jobs:
  airskiff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: hack/run
