name: Workflow Gate
description: Gate workflow based on Trivy scan results

inputs:
  generate-sbom:
    default: "false"
    description: Generate SBOM and submit results to Dependency Graph
  upload-scan-result:
    default: "false"
    description: Upload scan results to GitHub Security tab

runs:
  using: composite
  steps:
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # v0.24.0 https://github.com/aquasecurity/trivy-action/commit/6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
      with:
        exit-code: 1
        format: sarif
        hide-progress: false
        ignore-unfixed: true
        output: trivy-results.sarif
        scan-type: fs

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@b8efe4dc6ab6d31abe3ec159420d2a4916880800 # v3.26.6 https://github.com/github/codeql-action/commit/b8efe4dc6ab6d31abe3ec159420d2a4916880800
      if: ${{ inputs.upload-scan-result == 'true' }}
      with:
        sarif_file: trivy-results.sarif

    - name: Run Trivy SBOM and submit results to Dependency Graph
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # v0.24.0 https://github.com/aquasecurity/trivy-action/commit/6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
      if: ${{ inputs.generate-sbom == 'true' }}
      with:
        format: github
        github-pat: ${{ github.token }}
        image-ref: .
        output: dependency-results.sbom.json
        scan-type: fs
