name: Build

on:
  push:
    paths:
      - build/img/**
      - build/scripts/init-devos.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build Container
        uses: ./.github/actions/build
        with:
          build-container-image: true
          container-image-file: build/img/devos/Dockerfile
          container-image-name: devos
          container-image-repo-password: ${{ secrets.GHCR_TOKEN }}
          container-image-repo-username: ${{ github.repository_owner }}
          push-container-image: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
