name: Contiuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  bot:
    uses: ./.github/workflows/ondemand/bot.yml
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write

  sonarqube:
    uses: ./.github/workflows/gate/sonarqube.yml
  trivy:
    uses: ./.github/workflows/gate/trivy.yml
  devos:
    uses: ./.github/workflows/gate/devos.yml

  scorecard:
    uses: ./.github/workflows/ondemand/scorecard.yml
    permissions:
      contents: write
      id-token: write
      security-events: write
