name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  bot:
    uses: ./.github/workflows/bot.yml
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
  # devos:
  #   uses: ./.github/workflows/devos.yml
  trivy:
    uses: ./.github/workflows/trivy.yml
    permissions:
      contents: write
      id-token: write
      security-events: write
  scorecard:
    uses: ./.github/workflows/scorecard.yml
    permissions:
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      id-token: write
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
  # sonarqube:
  #   uses: ./.github/workflows/sonarqube.yml
